# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metorial < Formula
  desc "Official CLI for the Metorial platform"
  homepage "https://metorial.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metorial/cli/releases/download/v0.1.1/metorial_0.1.1_darwin_amd64.tar.gz"
      sha256 "ef4d94fae940f715a9e0884781cace8f6dee27421a4d60a24006881fbc844b64"

      define_method(:install) do
        bin.install "metorial"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metorial/cli/releases/download/v0.1.1/metorial_0.1.1_darwin_arm64.tar.gz"
      sha256 "bd13ab5916acf5e058f330986eaaa4538d15acf05d16e41739793c3c6580b719"

      define_method(:install) do
        bin.install "metorial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.1/metorial_0.1.1_linux_amd64.tar.gz"
      sha256 "92152eaeffca7e6a4cba34ca0835bb801e18c3d0900abdadf2276b3b3dfa6307"
      define_method(:install) do
        bin.install "metorial"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.1/metorial_0.1.1_linux_arm64.tar.gz"
      sha256 "b1e84ac5cea0df48b58f74d2d2c3303d0b0c7836d3f3fe7d20a121647c811015"
      define_method(:install) do
        bin.install "metorial"
      end
    end
  end

  test do
    system "#{bin}/metorial", "version"
  end
end
