# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metorial < Formula
  desc "Official CLI for Metorial integrations and MCP tools"
  homepage "https://metorial.com"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metorial/cli/releases/download/v0.1.3/metorial_0.1.3_darwin_amd64.tar.gz"
      sha256 "53e54a9ee2ac47590ef464c87385234ff3c28b3489a3df598d760c437552a721"

      define_method(:install) do
        bin.install "metorial"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metorial/cli/releases/download/v0.1.3/metorial_0.1.3_darwin_arm64.tar.gz"
      sha256 "b4451925cd85ddc2f14f495e631c8364eb3f2191b404c0c020f5302dc2e9419e"

      define_method(:install) do
        bin.install "metorial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.3/metorial_0.1.3_linux_amd64.tar.gz"
      sha256 "e8c6e59fc0a4d42acaeb0515ea3933d34ec68bafeffcb289e58a485bb4d2c4a3"
      define_method(:install) do
        bin.install "metorial"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.3/metorial_0.1.3_linux_arm64.tar.gz"
      sha256 "72018ed7613c0133dbdf26955e1b5f28349b1e692b6ad746215f428b9ad85495"
      define_method(:install) do
        bin.install "metorial"
      end
    end
  end

  test do
    system "#{bin}/metorial", "version"
  end
end
