# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetorialAdmin < Formula
  desc "Official admin CLI for the Metorial Magnetar API"
  homepage "https://metorial.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metorial/cli/releases/download/v0.1.2/metorial-admin_0.1.2_darwin_amd64.tar.gz"
      sha256 "aa7ea177d213a9a098250639fdc27789419bea66192fa75e2b1395ba895ff72a"

      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metorial/cli/releases/download/v0.1.2/metorial-admin_0.1.2_darwin_arm64.tar.gz"
      sha256 "df47fa4f1826f00e0f59be76709ccf612f6752437bb0034c3b540c5f32c323f1"

      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.2/metorial-admin_0.1.2_linux_amd64.tar.gz"
      sha256 "ba1b26cd46f382b1ccfb62926a3d5191ac087b22db367d7f31fd7320c891c7a5"
      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.2/metorial-admin_0.1.2_linux_arm64.tar.gz"
      sha256 "7790e40bb06a81d0afd57caf41e2430bdae52686ac41cbb3e66fda2510da4935"
      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
  end

  test do
    system "#{bin}/metorial-admin", "version"
  end
end
