# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetorialAdmin < Formula
  desc "Official admin CLI for the Metorial Magnetar API"
  homepage "https://metorial.com"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metorial/cli/releases/download/v0.1.4/metorial-admin_0.1.4_darwin_amd64.tar.gz"
      sha256 "de9768befdd5e649ee3ec809db25c662005ae342e5842a052d76674f400eb5b3"

      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metorial/cli/releases/download/v0.1.4/metorial-admin_0.1.4_darwin_arm64.tar.gz"
      sha256 "c5f4dfbba6a03cd1a50336bfca3bd327a1de13303476cc85663856f58012a37b"

      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.4/metorial-admin_0.1.4_linux_amd64.tar.gz"
      sha256 "60b9f9951f6668ef82dbdca1f4cb5b9cad2f26e0fb626b110b52c27735a9a4f3"
      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.4/metorial-admin_0.1.4_linux_arm64.tar.gz"
      sha256 "917e23c59aa3056ea1bba2f08135537c733665d8e4a6a879763082144fd85d4e"
      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
  end

  test do
    system "#{bin}/metorial-admin", "version"
  end
end
