# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metorial < Formula
  desc "Official CLI for Metorial integrations and MCP tools"
  homepage "https://metorial.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metorial/cli/releases/download/v0.1.2/metorial_0.1.2_darwin_amd64.tar.gz"
      sha256 "d26713a4b3cedc1a92592e462e87ce159e4582a689b77329a06cba872c34f8c8"

      define_method(:install) do
        bin.install "metorial"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metorial/cli/releases/download/v0.1.2/metorial_0.1.2_darwin_arm64.tar.gz"
      sha256 "e8eadeed862ae87adbe2790a5ed8394c7b2a691500331b3064ece45e7290f3fc"

      define_method(:install) do
        bin.install "metorial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.2/metorial_0.1.2_linux_amd64.tar.gz"
      sha256 "2bc6a2f013493e9657ec6df13cf4022a02fd7ede2d5843747449839de5a2d4c4"
      define_method(:install) do
        bin.install "metorial"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.2/metorial_0.1.2_linux_arm64.tar.gz"
      sha256 "20dc4584cc8e08cc7996b50218609fac3d4750636ecf6f9fe1d21df9d59b725e"
      define_method(:install) do
        bin.install "metorial"
      end
    end
  end

  test do
    system "#{bin}/metorial", "version"
  end
end
