# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MetorialAdmin < Formula
  desc "Official admin CLI for the Metorial Magnetar API"
  homepage "https://metorial.com"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metorial/cli/releases/download/v0.1.3/metorial-admin_0.1.3_darwin_amd64.tar.gz"
      sha256 "920dcf26a4d4bfae0c8e32a3aed93b13e026eeabd181c8eae785c3bcfeaa478a"

      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metorial/cli/releases/download/v0.1.3/metorial-admin_0.1.3_darwin_arm64.tar.gz"
      sha256 "dddad6c59b1c917f93b028a5e683f1d9b18158e89fd1bdb1aaa37b14fe369b42"

      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.3/metorial-admin_0.1.3_linux_amd64.tar.gz"
      sha256 "a16d254c4d15cb51475c5c97e5eec5313d4f8fecb232344c3420960dc1bfb72d"
      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metorial/cli/releases/download/v0.1.3/metorial-admin_0.1.3_linux_arm64.tar.gz"
      sha256 "915c4cd717883d06d7cdd350ae5f834092a050d6e8bb18581f9953be5b16d5f7"
      define_method(:install) do
        bin.install "metorial-admin"
      end
    end
  end

  test do
    system "#{bin}/metorial-admin", "version"
  end
end
